---
- name: Ensure configurator etc directory exists
  ansible.builtin.file:
    path: "{{ configurator_etc_dir }}"
    state: directory
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "0755"

- name: Ensure configurator etc configs directory exists
  ansible.builtin.file:
    path: "{{ configurator_etc_configs_dir }}"
    state: directory
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "0755"

- name: Ensure warehouse bin directory exists
  ansible.builtin.file:
    path: "{{ warehouse_root }}/bin"
    state: directory
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "0755"

- name: Copy configurator binary
  ansible.builtin.copy:
    src: "{{ configurator_src }}"
    dest: "{{ configurator_dest }}"
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "{{ configurator_mode }}"
