---
- name: Ensure keys mountpoints exist
  ansible.builtin.file:
    path: "{{ item.keys_mountpoint }}"
    state: directory
    owner: "{{ storage_owner }}"
    group: "{{ storage_group }}"
    mode: "0755"
  loop: "{{ ansible_facts['storage_drives'] }}"

- name: Ensure encrypted mountpoints exist
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
    owner: "{{ storage_owner }}"
    group: "{{ storage_group }}"
    mode: "0755"
  loop: "{{ ansible_facts['storage_drives'] }}"

- name: Configure crypttab for encrypted partitions
  ansible.builtin.lineinfile:
    path: /etc/crypttab
    regexp: "^{{ item.name }}_crypt\\s"
    line: "{{ item.name }}_crypt\tUUID={{ item.luks_uuid }}\t{{ item.keyfile }}\tluks,noauto"
    create: true
    owner: root
    group: root
    mode: "0640"
  loop: "{{ ansible_facts['storage_drives'] }}"

- name: Configure fstab for keys partitions
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^UUID={{ item.keys_part_uuid }}\\s"
    line: "UUID={{ item.keys_part_uuid }}\t{{ item.keys_mountpoint }}\t{{ item.fstype }}\tnofail\t0\t0"
  loop: "{{ ansible_facts['storage_drives'] }}"

- name: Configure fstab for encrypted partitions
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: "^/dev/mapper/{{ item.name }}_crypt\\s"
    line: "/dev/mapper/{{ item.name }}_crypt\t{{ item.mountpoint }}\t{{ item.fstype }}\tnofail,noauto\t0\t0"
  loop: "{{ ansible_facts['storage_drives'] }}"
