---
- name: Create Immich directory
  ansible.builtin.file:
    path: "{{ immich_dir }}"
    state: directory
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "0750"

- name: Deploy Immich docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ immich_dir }}/docker-compose.yml"
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "0640"

- name: Deploy Immich .env file
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ immich_dir }}/.env"
    owner: "{{ warehouse_owner }}"
    group: "{{ warehouse_owner }}"
    mode: "0640"
  no_log: true
